MVC_Programs/MVC_Beginform/MVC_Beginform/Models/User_Model.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MVC_Beginform.Models
{
    public class User_Model
    {
        public string UserName { get; set; }
        public int Age { get; set; }
        public string City { get; set; }

    }
}

MVC_Programs/MVC_Beginform/MVC_Beginform/Controllers/homeController.cs
using MVC_Beginform.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace MVC_Beginform.Controllers
{
    public class homeController : Controller
    {
        // GET: home
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(User_Model um)
        {
            return View(um);
        }

    }
}

MVC_Programs/MVC_Beginform/MVC_Beginform/Views/home/Index.cshtml
@using MVC_Beginform.Models
@model User_Model
@{
    ViewBag.Title = "Index";
}

<h1>HTML BEGIN FOR</h1>

@using (Html.BeginForm("Index", "home", FormMethod.Post))
{
    <span>Enter Your Name:</span> @Html.TextBoxFor(m => m.UserName)
    <br />
    <span>Enter Your Age: </span> @Html.TextBoxFor(m => m.Age)
    <br />
    <span>Enter Your City: </span>@Html.TextBoxFor(m => m.City)
    <br />

    <input id="Submit" type="submit" value="submit" />
}

<hr />

<strong>User Name: </strong> @Html.DisplayFor(m => m.UserName)
<br />
<strong>User Age: </strong> @Html.DisplayFor(m => m.Age)
<br />
<strong>User City: </strong> @Html.DisplayFor(m => m.City)
<br />